# 1. Execute on push

jobs:
  lint_check:
    # 2. Run on latest Ubuntu

    steps:
      - name: Checkout
      # 3. Checkout repository

      - name: Run linter
      # 4. Run Rust's linter to check for warnings and errors
