on: [push]

env:
  RUST_VERSION: 1.70.0

jobs:
  clippy-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{env.RUST_VERSION}}
          profile: minimal
          override: true

      - name: Build
        run: cargo build --all-targets

      - name: Build and run Clippy
        run: |
          cargo install --force clippy
          cargo clippy --all-targets --all-features -- -D warnings

      - name: Check for errors and warnings
        run: .github/workflows/scripts/clippy.sh